openapi: 3.0.3
info:
  title: Pet API
  version: "1.0.0"
paths:
  /pets:
    get:
      summary: List all pets
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './components/pet.yaml#/Pet'
