name: API Breaking Change Check

on:
  push:
    paths:
      - 'api/**'
      - 'scripts/**'

jobs:
  check-breaking-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install oasdiff
        run: |
          curl -fsSL https://raw.githubusercontent.com/oasdiff/oasdiff/main/install.sh | sh
          # oasdiff is now installed to /usr/local/bin by the script

      - name: Run Breaking Change Check
        run: bash scripts/check-breaking.sh
